# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.iamctl.name }}
  name: {{ .Values.iamctl.name }}
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.iamctl.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.iamctl.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.iamctl.name }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - sleep
        - "3600"
        image: "{{ .Values.iamctl.image.repository }}:{{ .Values.iamctl.image.tag | default .Chart.AppVersion }}"
        name: {{ .Values.iamctl.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        resources:
          limits: 
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 250m 
            memory: 200Mi
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: IAM_AUTHZ_SERVER_HOST
            value: iam-authz-server
          - name: IAM_APISERVER_HOST
            value: iam-apiserver
          - name: IAM_PUMP_HOST
            value: iam-pump
          - name: IAM_WATCHER_HOST
            value: iam-watcher
        volumeMounts:
        - mountPath: /etc/iam/{{ .Values.iamctl.name }}.yaml
          name: iam
          subPath: {{ .Values.iamctl.name }}.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: {{ .Values.iamctl.name }}.yaml
            path: {{ .Values.iamctl.name }}.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
