---
# Source: iam/templates/iam-apiserver-service.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-apiserver
  name: iam-apiserver
spec:
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: rpc
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: iam-apiserver
  sessionAffinity: None
  type: ClusterIP
---
# Source: iam/templates/iam-authz-server-service.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-authz-server
  name: iam-authz-server
spec:
  ports:
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: iam-authz-server
  sessionAffinity: None
  type: ClusterIP
---
# Source: iam/templates/iam-pump-service.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-pump
  name: iam-pump
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7070
    targetPort: 7070
  selector:
    app: iam-pump
  sessionAffinity: None
  type: ClusterIP
---
# Source: iam/templates/iam-watcher-service.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-watcher
  name: iam-watcher
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: iam-watcher
  sessionAffinity: None
  type: ClusterIP
---
# Source: iam/templates/iam-apiserver-deployment.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam-apiserver
  name: iam-apiserver
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iam-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iam-apiserver
    spec:
      imagePullSecrets:
        - name: ccr-registry
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iam-apiserver
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/iam/bin/iam-apiserver
        - --config=/etc/iam/iam-apiserver.yaml
        image: "ccr.ccs.tencentyun.com/marmotedu/iam-apiserver-amd64:v1.6.2"
        name: iam-apiserver
        securityContext:
            {}
        ports:
        - containerPort: 8443
          name: secure
          protocol: TCP
        - containerPort: 8080
          name: insecure
          protocol: TCP
        - containerPort: 8081
          name: rpc 
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/iam/iam-apiserver.yaml
          name: iam
          subPath: iam-apiserver.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: iam-apiserver.yaml
            path: iam-apiserver.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
---
# Source: iam/templates/iam-authz-server-deployment.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam-authz-server
  name: iam-authz-server
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iam-authz-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iam-authz-server
    spec:
      imagePullSecrets:
        - name: ccr-registry
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iam-authz-server
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/iam/bin/iam-authz-server
        - --config=/etc/iam/iam-authz-server.yaml
        image: "ccr.ccs.tencentyun.com/marmotedu/iam-authz-server-amd64:v1.6.2"
        name: iam-authz-server
        securityContext:
            {}
        ports:
        - containerPort: 9443
          name: secure
          protocol: TCP
        - containerPort: 9090
          name: insecure
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/iam/iam-authz-server.yaml
          name: iam
          subPath: iam-authz-server.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: iam-authz-server.yaml
            path: iam-authz-server.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
---
# Source: iam/templates/iam-pump-deployment.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam-pump
  name: iam-pump
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iam-pump
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iam-pump
    spec:
      imagePullSecrets:
        - name: ccr-registry
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iam-pump
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/iam/bin/iam-pump
        - --config=/etc/iam/iam-pump.yaml
        image: "ccr.ccs.tencentyun.com/marmotedu/iam-pump-amd64:v1.6.2"
        name: iam-pump
        securityContext:
            {}
        ports:
        - containerPort: 9443
          name: secure
          protocol: TCP
        - containerPort: 9090
          name: insecure
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7070
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7070
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 7070
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/iam/iam-pump.yaml
          name: iam
          subPath: iam-pump.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: iam-pump.yaml
            path: iam-pump.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
---
# Source: iam/templates/iam-watcher-deployment.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam-watcher
  name: iam-watcher
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iam-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iam-watcher
    spec:
      imagePullSecrets:
        - name: ccr-registry
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iam-watcher
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/iam/bin/iam-watcher
        - --config=/etc/iam/iam-watcher.yaml
        image: "ccr.ccs.tencentyun.com/marmotedu/iam-watcher-amd64:v1.6.2"
        name: iam-watcher
        securityContext:
            {}
        ports:
        - containerPort: 9443
          name: secure
          protocol: TCP
        - containerPort: 9090
          name: insecure
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5050
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5050
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 5050
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/iam/iam-watcher.yaml
          name: iam
          subPath: iam-watcher.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: iam-watcher.yaml
            path: iam-watcher.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
---
# Source: iam/templates/iamctl-deployment.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iamctl
  name: iamctl
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: iamctl
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iamctl
    spec:
      imagePullSecrets:
        - name: ccr-registry
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - iamctl
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - sleep
        - "3600"
        image: "ccr.ccs.tencentyun.com/marmotedu/iamctl-amd64:v1.6.2"
        name: iamctl
        securityContext:
            {}
        resources:
          limits: 
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 250m 
            memory: 200Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: IAM_AUTHZ_SERVER_HOST
            value: iam-authz-server
          - name: IAM_APISERVER_HOST
            value: iam-apiserver
          - name: IAM_PUMP_HOST
            value: iam-pump
          - name: IAM_WATCHER_HOST
            value: iam-watcher
        volumeMounts:
        - mountPath: /etc/iam/iamctl.yaml
          name: iam
          subPath: iamctl.yaml
        - mountPath: /etc/iam/cert
          name: iam-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: iamctl.yaml
            path: iamctl.yaml
          name: iam
        name: iam
      - configMap:
          defaultMode: 420
          name: iam-cert
        name: iam-cert
---
# Source: iam/templates/hpa.yaml
# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.
