.nh
.TH IAM(1) iam User Manuals
Eric Paris
Jan 2015

.SH NAME
.PP
iamctl policy create - Create a authorization policy resource


.SH SYNOPSIS
.PP
\fBiamctl policy create\fP [OPTIONS]


.SH DESCRIPTION
.PP
Create a authorization policy resource.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--alsologtostderr\fP=false
	log to standard error as well as files

.PP
\fB-c\fP, \fB--config\fP=""
	Read configuration from specified \fB\fCFILE\fR, support JSON, TOML, YAML, HCL, or Java properties formats.

.PP
\fB--iamconfig\fP=""
	Path to the iamconfig file to use for CLI requests

.PP
\fB--log-backtrace-at\fP=:0
	when logging hits line file:N, emit a stack trace

.PP
\fB--log-dir\fP=""
	If non-empty, write log files in this directory

.PP
\fB--logtostderr\fP=false
	log to standard error instead of files

.PP
\fB--match-server-version\fP=false
	Require server version to match client version

.PP
\fB--profile\fP="none"
	Name of profile to capture. One of (none|cpu|heap|goroutine|threadcreate|block|mutex)

.PP
\fB--profile-output\fP="profile.pprof"
	Name of the file to write the profile to

.PP
\fB-s\fP, \fB--server.address\fP=""
	The address and port of the IAM API server

.PP
\fB--server.certificate-authority\fP=""
	Path to a cert file for the certificate authority

.PP
\fB--server.insecure-skip-tls-verify\fP=false
	If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB--server.max-retries\fP=0
	Maximum number of retries.

.PP
\fB--server.retry-interval\fP=1s
	The interval time between each attempt.

.PP
\fB--server.timeout\fP=30s
	The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB--server.tls-server-name\fP=""
	Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used

.PP
\fB--stderrthreshold\fP=2
	logs at or above this threshold go to stderr

.PP
\fB--user.client-certificate\fP=""
	Path to a client certificate file for TLS

.PP
\fB--user.client-key\fP=""
	Path to a client key file for TLS

.PP
\fB--user.password\fP=""
	Password for basic authentication to the API server

.PP
\fB--user.secret-id\fP=""
	SecretID for JWT authentication to the API server

.PP
\fB--user.secret-key\fP=""
	SecretKey for jwt authentication to the API server

.PP
\fB--user.token\fP=""
	Bearer token for authentication to the API server

.PP
\fB--user.username\fP=""
	Username for basic authentication to the API server

.PP
\fB-v\fP, \fB--v\fP=0
	log level for V logs

.PP
\fB--version\fP=false
	Print version information and quit.

.PP
\fB--vmodule\fP=
	comma-separated list of pattern=N settings for file-filtered logging


.SH EXAMPLE
.PP
.RS

.nf
  # Create a authorization policy
  iamctl policy create foo '{"description":"This is a updated policy","subjects":["users:<peter|ken>","users:maria","groups:admins"],"actions":["delete","<create|update>"],"effect":"allow","resources":["resources:articles:<.*>","resources:printer"],"conditions":{"remoteIPAddress":{"type":"CIDRCondition","options":{"cidr":"192.168.0.1/16"}}}}'

.fi
.RE


.SH SEE ALSO
.PP
\fBiamctl-policy(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the marmotedu source material, but hopefully they have been automatically generated since!
